services:
  web:
    container_name: web
    image: cake-pake:latest
    ports:
      - "8080:8080"
      - "5555:5555"
    restart: always
    environment:
      - url=jdbc:postgresql://db:5432/cake
      - username=postgres
      - password=postgres
    logging:
      options:
        max-size: 50m
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cake
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cake
      - DB_HOST=127.0.0.1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cake
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: aka.beka94@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - cake
    restart: always
networks:
  cake:
    external: true
version: '2.1'